In [1]:
import numpy as np


In [2]:
A = np.array([[1,2],[3,4]])



In [3]:
#lets perform Singular Value Decomposition (SVD) on the matrix A
U , D , Vt = np.linalg.svd(A) #U is the left singular vectors, D is the singular values, and Vt is the right
#np.linalg.svd returns the singular values in descending order, so we can use them to reconstruct the original matrix A
#we can also use the singular values to perform dimensionality reduction by keeping only the top k singular values and their corresponding singular vectors


In [4]:
D = np.diag(D) #convert the singular values into a diagonal matrix
A_reconstructed = np.dot(U, np.dot(D, Vt)) #reconstruct the original matrix A using the singular values and singular vectors
print("Original Matrix A:")
print(A)
print("Reconstructed Matrix A:")
print(A_reconstructed)
print("Left Singular Vectors (U):")
print(U)
print("Singular Values (D):")
print(D)
print("Right Singular Vectors (Vt):")
print(Vt)


Original Matrix A:
[[1 2]
 [3 4]]
Reconstructed Matrix A:
[[1. 2.]
 [3. 4.]]
Left Singular Vectors (U):
[[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
Singular Values (D):
[[5.4649857  0.        ]
 [0.         0.36596619]]
Right Singular Vectors (Vt):
[[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


In [5]:
print(f"is the original matrix A equal to the reconstructed matrix A? {np.allclose(A, A_reconstructed)}")

is the original matrix A equal to the reconstructed matrix A? True
